# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate, jekyll-sitemap]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://kickinbahk.github.io/
# baseurl: /home/
title: iOS Developer & Twitch Streamer - kickinbahk
author: Josiah Mory
description:  Josiah Mory; formerly a musician, currently an iOS developer. I stream iOS app developement on Twitch.
avatar: profile.png
email: josiah@kickinbahkproductions.com
github: kickinbahk
twitter: kickinbahk
linkedin: josiahmory
stackoverflow: users/4009231/kickinbahk
#Comment out if you don't want disqus
# disqus: kickinbahk
google_analytics: UA-64777363-2


# needed for travis-ci build
exclude: [vendor]
